/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef DK_ENTITY_H
#define DK_ENTITY_H

/* Game-owned state. No engine edict, ABI mirror, or serialized function pointer. */
typedef struct {
    unsigned int id;
    char *killtarget;
    char *map;
    char *targets[3];
    char *uniqueid;
    char *key;
    char *parentTarget;
    unsigned int parentId;
    unsigned int monitorId;
    int monitorStart, monitorUnlock;
    float cameraFov;
    int delay;
    int nextUse;
    int uses;
    int moverKind;
    int decorKind;
    int objectMove;
    int animationLoop;
    int supply;
    int supplyMaximum;
    int recharge;
    int rechargeTime;
    char *mediaPath;
    int soundIndices[7];
    int soundCount, soundEnabled, soundDelay, soundMinimum;
    unsigned int soundRandom;
    int effectActive, effectOnTime, effectOffTime, effectStopTime, effectNextCycle;
    unsigned int combatHitBits[MAX_GENTITIES / 32];
    int moverAccel, moverBounce, moverDust, moverQuake;
    float moverMass;
    int monsterAttack;
    int lightStyle;
    int environmentStyle;
    float environmentReverb, environmentGain;
    float effectChance, effectGroundChance;
    int moverAngular;
    int moverPaused;
    int moverInitialized;
    int moverArrival;
    int forceMove;
    vec3_t rotationDelta;
    vec3_t rotationRate;
    vec3_t secretEnd;
    int groundedFlight;
    int actorKind;
    int action;
    int actionTime;
    int destinationId;
    int firstFrame;
    int lastFrame;
    int animationTime;
    int experience;
    int inventory;
    int ammunition[32];
    int armor;
    int armorAbsorption;
    int attributes[5];
    int actorLevel;
    int maxHealth;
    int companionOrder;
    int companionEnabled;
    unsigned int pickupId;
    int pickupRetry;
    char *companionName;
    char *triggerAnimation;
    int triggerToggle;
    vec3_t triggerDestination;
    int animationRate;
    int animationIndex;
    int animationCursor;
    unsigned int actorRandom;
    int attackGroup;
    int lastSeenTime;
    vec3_t lastSeenOrigin;
    vec3_t actorVelocity, roamGoal;
    int roamUntil;
    int abilityState;
    int abilityTime;
    int abilityCharges;
    int scriptUntil;
    int ignorePlayer;
    int blockedSince;
    int yieldUntil;
    char *pathTarget;
    char *movingAnimation;
    char *aiScript;
    char *deathTarget;
    char *deathSpawn;
    char *spawnClass;
    char *spawnId;
    char *cineScript;
    char *cineKill;
    char *cineTrigger;
    int cinematicOwned;
    int cinematicControlled;
    int moveActive;
    vec3_t moveGoal;
    float speedOverride;
    float savedSpeed;
    float walkSpeed;
    float runSpeed;
    float yawSpeed;
    float sightRange, attackRange, speakRange;
    int evadeUntil, coverTime, evadeKind;
    vec3_t evadeGoal;
    int fireInterval, attackDamage, attackRandomDamage;
    int turretFrames, turretEnabled;
    float savedWalkSpeed;
    float savedYawSpeed;
    vec3_t turnGoal;
    int turnActive;
    int cinematicCompleted;
    int eventFirst;
    int eventCount;
    int eventStart;
    int eventCursor;
    unsigned int ownerId;
    int expires;
    int combatState;
    int combatCount;
    int combatNext;
    int combatEnd;
    int weaponHoldUntil;
    unsigned int weaponParentId; /* Controller ownership, separate from mover attachments. */
    int poisonEnd;
    int poisonNext;
    int poisonInterval;
    int burnEnd;
    int burnNext;
    int freezeNext;
    int freezeStart;
    int healingUser;
    float poisonDamage;
    float poisonFraction;
    float freezeLevel;
    int combatTargets[32];
    float launchOrigin[3];
    int projectile;
    int status;
    int statusExpires;
    int statusTick;
    unsigned int statusOwnerId;
} dkEntity_t;

#endif
