/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef DK_GAME_H
#define DK_GAME_H

gentity_t *DK_FindEntity(unsigned int id);
void DK_WriteTravel(gentity_t *player);
void DK_ReadTravel(gentity_t *player);
qboolean DK_ClientCommand(gentity_t *player, const char *command);
qboolean DK_CanUse(gentity_t *target);
qboolean DK_ObjectiveMode(void);
void DK_InitMultiplayer(void);
qboolean DK_SpawnMultiplayer(gentity_t *entity);
void DK_CheckMultiplayer(void);
void DK_RunMultiplayer(void);
void DK_DropObjective(gentity_t *player);
gentity_t *DK_TeamSpawn(int team, vec3_t origin, vec3_t angles);
gentity_t *DK_ObjectiveGoal(gentity_t *player);
qboolean DK_ObjectiveProtects(gentity_t *player, int mod);
void DK_InitBots(qboolean restart);
int DK_BotFrame(int time);
qboolean DK_ConnectBot(int client);
void DK_DisconnectBot(int client);
void DK_AddBotCommand(void);
void DK_LoadActors(void);
float DK_ActorMass(gentity_t *actor);
void DK_LoadDecor(void);
qboolean DK_SpawnWorldEffect(gentity_t *entity);
void DK_RestoreWorldEffect(gentity_t *entity);
qboolean DK_ValidateWorldEffect(gentity_t *entity);
qboolean DK_ValidateDecorState(gentity_t *entity);
void DK_WorldDebris(gentity_t *entity, int material);
void DK_ActorGib(gentity_t *actor, gentity_t *attacker, const vec3_t mins, const vec3_t maxs,
                 int fragtype, float mass, int damage);
void DK_WorldMusic(void);
qboolean DK_SpawnInteraction(gentity_t *entity);
void DK_RestoreInteraction(gentity_t *entity);
void DK_RunMonitors(void);
qboolean DK_StopMonitor(gentity_t *player, qboolean force);
void DK_SetMusic(const char *name);
int DK_SoundIndex(const char *name);
qboolean DK_SpawnMedia(gentity_t *entity);
void DK_RestoreMedia(gentity_t *entity);
qboolean DK_SpawnDecor(gentity_t *entity);
void DK_RestoreDecor(gentity_t *entity);
void DK_LoadNavigation(const char *map);
void DK_LoadGroundNavigation(const char *map);
qboolean DK_GroundWaypoint(gentity_t *actor, const vec3_t destination, int flags, vec3_t waypoint, int *travel);
qboolean DK_NavigationGoal(gentity_t *actor, const vec3_t destination, int mode, int target, vec3_t result);
qboolean DK_ValidateActorState(gentity_t *actor, const char *savedMap);
void DK_RestoreActor(gentity_t *actor);
qboolean DK_SpawnActor(gentity_t *ent);
qboolean DK_IsCompanion(gentity_t *ent);
void DK_InitCompanionInventory(gentity_t *actor);
void DK_WriteCompanionTravel(void);
void DK_UpdateCompanionStatus(void);
void DK_StartCompanions(gentity_t *player);
qboolean DK_CompanionsReady(gentity_t *player, int flags);
void DK_TouchActorTriggers(gentity_t *actor);
qboolean DK_TriggerContact(const vec3_t mins, const vec3_t maxs, gentity_t *trigger);
qboolean DK_SpawnCompanionEntity(gentity_t *ent);
float DK_CompanionItemValue(gentity_t *actor, gentity_t *item);
qboolean DK_CompanionPickup(gentity_t *actor, gentity_t *item);
int DK_FireCompanionWeapon(gentity_t *actor, gentity_t *target);
qboolean DK_CompanionCommand(gentity_t *player, const char *command);
qboolean DK_SpawnActorCommand(gentity_t *player, const char *command);
int DK_ActorAnimate(gentity_t *ent, const char *name, float repeats);
qboolean DK_ActorState(gentity_t *ent, const char *state, const char *argument);
void DK_ActorStrike(gentity_t *owner, gentity_t *target, int weapon, const vec3_t offset,
                   float speed, int damage, float range, float spreadX, float spreadZ);
void DK_ActorMoveTo(gentity_t *actor, const vec3_t goal);
void DK_ActorHold(gentity_t *actor);
void DK_InitCinematics(void);
void DK_Worldspawn(void);
void DK_RunCinematic(void);
qboolean DK_StartCinematic(const char *name, gentity_t *trigger, gentity_t *activator);
void DK_StopCinematic(qboolean completed);
void DK_SkipCinematic(void);
void DK_CinematicFinished(gentity_t *trigger, gentity_t *activator);
void DK_LoadScripts(const char *map);
void DK_RunScripts(void);
qboolean DK_StartScript(const char *name, gentity_t *owner, gentity_t *activator, qboolean urgent);
qboolean DK_UseActorScript(gentity_t *actor, gentity_t *activator);
gentity_t *DK_FindNamed(const char *name);
void DK_FireNamed(const char *name, gentity_t *source, gentity_t *activator);
void DK_GiveAllWeapons(gentity_t *player);
qboolean DK_GiveWeapon(gentity_t *player, int weapon, int rounds);
float DK_CompanionWeaponValue(gentity_t *actor, int weapon);
void DK_RestoreWeaponItem(gentity_t *item);
qboolean DK_WeaponSplash(int weapon);
float DK_BotWeaponRange(int weapon);
float DK_BotWeaponScore(gentity_t *owner, int weapon, float distance);
qboolean DK_BotWeaponAttack(const playerState_t *ps, int weapon, qboolean ready);
void DK_WeaponKilled(gentity_t *victim, gentity_t *attacker, int mod);
int DK_WeaponControllerLimit(int weapon);
qboolean DK_ScriptWeaponCommand(gentity_t *player, const char *command);
int DK_WeaponSwordExperience(int weapon, int health);
qboolean DK_WeaponSlaysRevenants(int weapon);
qboolean DK_ValidateWeaponEntity(const gentity_t *ent);
void DK_FireWeapon(gentity_t *ent);
int DK_DetonateCharges(gentity_t *owner);
void DK_RestoreProjectile(gentity_t *ent);
void DK_RestoreWorldCallbacks(gentity_t *ent);
void DK_RestoreCompanionEntity(gentity_t *ent);
qboolean DK_SpawnMover(gentity_t *ent);
void DK_RunMovers(void);
void DK_SetupMovers(void);
void DK_SetupAttachments(void);
void DK_MoveAssembly(gentity_t *root);
void DK_TeleportAssembly(gentity_t *root, const vec3_t destination);
void DK_RepairSavedAttachments(const gentity_t *baseline, int count);
void DK_RestoreNativeMover(gentity_t *ent);
void DK_RestoreMover(gentity_t *ent);
void DK_RestoreItem(gentity_t *ent);
void DK_DropInventory(gentity_t *player);
void DK_DeathSpawn(gentity_t *source);
void DK_ProjectileImpact(gentity_t *ent, trace_t *trace);
void DK_RunStatus(void);
int DK_ModifyDamage(gentity_t *victim, gentity_t *attacker, int damage);
char *DK_ItemModel(const char *classname);
qboolean DK_SpawnItem(gentity_t *ent);
qboolean DK_HasKey(gentity_t *player, const char *name);
void DK_StartingInventory(gentity_t *player);
void DK_RunItemEffects(void);
int DK_PlayerWeaponLoop(gentity_t *player);
void DK_ColdWater(gentity_t *ent, qboolean protected);
void DK_AwardExperience(gentity_t *player, int amount, int swordAmount);
int trap_DK3SaveWrite(int version, const char *slot, const void *data, int length);
int trap_DK3SaveRead(int version, const char *slot, void *data, int capacity, qboolean previous);
qboolean trap_DK3HoldWorld(int version, qboolean hold);
qboolean DK_SaveReferenceExists(unsigned int id);
void DK_InitSaves(void);
qboolean DK_RestartAfterDeath(gentity_t *player);
qboolean DK_ArchiveLevel(gentity_t *player);
qboolean DK_RestoreVisited(gentity_t *player);
void DK_RunSaves(void);
qboolean DK_LoadRequested(gentity_t *player);
qboolean DK_SaveCommand(gentity_t *player, const char *command);
qboolean DK_ResumeSave(gentity_t *player);
qboolean DK_RestoringSave(void);
void DK_AdoptEntityId(gentity_t *ent, unsigned int id);
void DK_InitWorld(void);
void DK_InitEntity(gentity_t *ent);
void DK_PrepareEntity(gentity_t *ent);
qboolean DK_SpawnEntity(gentity_t *ent);
void DK_RunWorld(void);
void DK_PublishActors(void);
void DK_DropToxicBomb(gentity_t *owner, gentity_t *target, int damage, int phase);
void DK_ZapFlare(const vec3_t origin, const char *sprite, float scale, int duration);
void DK_UseTargets(gentity_t *ent, gentity_t *activator);
gentity_t *DK_SelectSpawn(vec3_t origin, vec3_t angles);
void DK_ClientSpawn(gentity_t *ent);

#endif
