/* SPDX-License-Identifier: GPL-2.0-or-later */
#include "dk_inventory.h"
#include <string.h>
const char *dk_keyClasses[DK_KEY_COUNT] = {
    "item_control_card_blue",
    "item_control_card_green",
    "item_control_card_red",
    "item_control_card_yellow",
    "item_keycard_cell",
    "item_lift_codes",
    "item_crypt_key",
    "item_hex_keystone",
    "item_quad_keystone",
    "item_trigon_keystone",
    "item_wyndrax_key",
    "item_horn",
    "item_spellbook",
    "item_drachma",
    "item_charcoal",
    "item_saltpeter",
    "item_sulphur",
    "item_bottle",
    "item_wood_chest",
    "item_black_chest",
    "item_rune_a",
    "item_rune_e",
    "item_rune_g",
    "item_rune_i",
    "item_rune_s",
    "item_purifier_shard1",
    "item_purifier_shard2_1",
    "item_purifier_shard2_2",
    "item_purifier_shard2_3",
    "item_purifier_shard2_4",
    "item_purifier_shard2_5",
    "item_purifier_shard3",
};
const char *dk_keyLabels[DK_KEY_COUNT] = {
    "Control card blue",
    "Control card green",
    "Control card red",
    "Control card yellow",
    "Keycard cell",
    "Lift codes",
    "Crypt key",
    "Hex keystone",
    "Quad keystone",
    "Trigon keystone",
    "Wyndrax key",
    "Horn",
    "Spellbook",
    "Drachma",
    "Charcoal",
    "Saltpeter",
    "Sulphur",
    "Bottle",
    "Wood chest",
    "Black chest",
    "Rune a",
    "Rune e",
    "Rune g",
    "Rune i",
    "Rune s",
    "Purifier shard1",
    "Purifier shard2 1",
    "Purifier shard2 2",
    "Purifier shard2 3",
    "Purifier shard2 4",
    "Purifier shard2 5",
    "Purifier shard3",
};

typedef struct { const char *classname, *model; } itemModel_t;
static const itemModel_t itemModels[] = {
    {"ammo_ionpack", "e1/wa_ion"}, {"ammo_c4", "e1/wa_c4"}, {"ammo_shells", "e1/wa_shot6"},
    {"ammo_rockets", "e1/wa_swindr"}, {"ammo_shocksphere", "e1/wa_shokwv"},
    {"ammo_tritips", "e2/wa_trident"}, {"ammo_venomous", "e2/wa_venom"}, {"ammo_zeus", "e2/wa_zeus"},
    {"ammo_bolts", "e3/wa_bolt"}, {"ammo_ballista", "e3/wa_bal"}, {"ammo_stavros", "e3/wa_stav"},
    {"ammo_wisp", "e3/a_wyndrx"}, {"ammo_bullets", "e4/wa_glock"}, {"ammo_ripgun", "e4/wa_slug"},
    {"ammo_slugger", "e4/wa_rip"}, {"ammo_cordite", "e4/a_cslug"}, {"ammo_kineticore", "e4/wa_kcore"},
    {"ammo_novabeam", "e4/wa_nova"}, {"ammo_metamaser", "e4/a_mmaser"},
    {"item_chromatic_armor", "e1/a1_ar2"}, {"item_plasteel_armor", "e1/a1_ar1"},
    {"item_silver_armor", "e2/a2_ar1"}, {"item_gold_armor", "e2/a2_ar2"},
    {"item_chainmail_armor", "e3/a3_ar1"}, {"item_black_adamant_armor", "e3/a3_ar2"},
    {"item_kevlar_armor", "e4/a4_ar1"}, {"item_ebonite_armor", "e4/a4_ar2"},
    {"item_goldensoul", "global/a_gsoul"}, {"item_megashield", "global/a_mshield"},
    {"item_invincibility", "global/a_invincibility"}, {"item_wraithorb", "global/a_wraithorb"},
    {"item_savegem", "global/a_savegem"}, {"item_power_boost", "global/a_pwrb"},
    {"item_attack_boost", "global/a_atkb"}, {"item_speed_boost", "global/a_spdb"},
    {"item_acro_boost", "global/a_acrb"}, {"item_vita_boost", "global/a_vtlb"},
    {"item_antidote", "global/a_antidote"}, {"item_envirosuit", "e4/a_envsuit"},
    {"item_control_card_blue", "e4/a4_clcbl"}, {"item_control_card_green", "e4/a4_clcgr"},
    {"item_control_card_yellow", "e4/a4_clcyl"}, {"item_keycard_cell", "e1/a1_clcrd"},
    {"item_lift_codes", "e4/d4_rock1"}, {"item_drachma", "e2/a2_drachma"}, {"item_horn", "e2/a2_horn"},
    {"item_rune_a", "e2/c_runea"}, {"item_rune_e", "e2/c_runee"}, {"item_rune_g", "e2/c_runeg"},
    {"item_rune_i", "e2/c_runei"}, {"item_rune_s", "e2/c_runes"},
    {"item_crypt_key", "e3/a3_crkey"}, {"item_wyndrax_key", "e3/a3_ltkey"}, {"item_spellbook", "e3/a3_bookw"},
    {"item_hex_keystone", "e3/a_hex"}, {"item_quad_keystone", "e3/a_quad"}, {"item_trigon_keystone", "e3/a_tri"},
    {"item_purifier_shard1", "e3/purifier_1"}, {"item_purifier_shard2_1", "e3/purifier_2"},
    {"item_purifier_shard2_2", "e3/purifier_2"}, {"item_purifier_shard2_3", "e3/purifier_2"},
    {"item_purifier_shard2_4", "e3/purifier_2"}, {"item_purifier_shard2_5", "e3/purifier_2"},
    {"item_purifier_shard3", "e3/purifier_3"}, {"item_black_chest", "e3/a_blackchest"},
    {"item_wood_chest", "e3/a_chest"}, {"item_ring_of_fire", "e3/a_ring_fire"},
    {"item_ring_of_undead", "e3/a_ringund"}, {"item_ring_of_lightning", "e3/a_ringlig"},
    {"item_bottle", "e4/a_bottle"}, {"item_sulphur", "e4/a_sulphur"},
    {"item_charcoal", "e4/a_charcoal"}, {"item_saltpeter", "e4/a_saltp"}
};


const char *DK_ItemModelName(const char *classname) {
    unsigned int i;
    for (i = 0; i < sizeof(itemModels) / sizeof(itemModels[0]); ++i)
        if (!strcmp(classname, itemModels[i].classname)) return itemModels[i].model;
    return NULL;
}
