# SPDX-License-Identifier: GPL-2.0-or-later
"""Build, compile, inspect and install one authored multiplayer map.

    python3 -B dkq3/tools/map_build.py --map japanDM [--source maps/japanDM] \
        [--prefix zig-out/native-dev] [--stages author,compile,aas,package,install] [--quality]

A map is authored in `maps/<name>/`: `materials.py` is the material table (the
generated `.shader` and the image manifest both come from it),
`build_blender.py` models the level into `<name>.blend` when the `.blend` is
missing or older than the script, and `map_author.py` exports that scene to
`<name>.map`. Everything derived afterwards is a build product under
`zig-out/map-dev/<name>/`: the private compiler tree, the BSP, the bot AAS, the
build report and the installable `zz-dk3-<name>.pk3`.

q3map2 runs against a private VFS rooted at `<work>/home/.q3a/baseq3` with `HOME`
pointed at it, so a map build reads and writes nothing outside its own tree; the
installation receives exactly one loose package plus its own `maps.cfg`
replacement. The converted packages are hash-checked by the launcher and the
preserved game stays untouched, so maps are always *added*, never rewritten.

Each stage reports what it proved. `--stages compile` alone reuses the exported
`.map`, and a compile that leaked, lost its vis, arrived unlit, or reached the
BSP without its shaders is a failure even when q3map2 exits 0.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys

import map_materials
import pk3
import q3bsp

Q3MAP2 = '/var/lib/flatpak/app/io.github.TTimo.GtkRadiant/x86_64/stable/active/files/gtkradiant/q3map2'
STAGES = ('author', 'compile', 'relight', 'aas', 'package', 'install')
# q3map2 prints "Unknown option" for every flag another stage owns, so those are
# not evidence of anything. These are.
FAILURES = ('Error opening', 'Error :', 'ERROR', 'leaked', 'Could not find visreachable',
            'MAX_MAP_ENTITIES', 'MAX_MAP_BRUSHES', 'WARNING: Couldn\'t load image texture',
            'unknown shader', 'using default shader', 'Couldn\'t find image for shader')
# `Couldn't find image for shader X` is the only thing q3map2 says when a face
# names a shader its script never defined. It then builds the surface with
# default parms -- opaque, lightmapped, CONTENTS_SOLID -- which is how a
# `trigger_hurt` volume became a 64-tall invisible wall across a japanDM
# street: the map wrote the material's table key and the block was filed
# under the `common/` path the entry declared. `map_materials.shader_text`
# defines both names now, and this marker is what keeps them honest.


def run(command, cwd=None, home=None, log=None, label='', env=None):
    """-> (returncode, transcript); the whole transcript is kept for the build log."""
    environment = dict(os.environ, **(env or {}))
    if home:
        environment['HOME'] = str(home)
    result = subprocess.run(command, cwd=cwd, env=environment, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, errors='replace')
    if log is not None:
        Path(log).parent.mkdir(parents=True, exist_ok=True)
        Path(log).write_text(result.stdout)
    if result.returncode:
        raise RuntimeError('%s exited %d; see %s\n%s' % (label or command[0], result.returncode, log or cwd,
                                                         '\n'.join(result.stdout.splitlines()[-20:])))
    return result.returncode, result.stdout


def load_table(source):
    """Import `maps/<name>/materials.py`, which holds only the material table."""
    path = Path(source) / 'materials.py'
    spec = importlib.util.spec_from_file_location('dk3_map_materials_table', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if not isinstance(getattr(module, 'MATERIALS', None), dict):
        raise RuntimeError('%s: MATERIALS must be a dict' % path)
    return module


def stage_tree(work, name, table, assets):
    """Write the compiler's VFS: generated shader script plus every image."""
    base = work / 'home' / '.q3a' / 'baseq3'
    (base / 'maps').mkdir(parents=True, exist_ok=True)
    (base / 'scripts').mkdir(parents=True, exist_ok=True)
    shader = base / 'scripts' / ('%s.shader' % name)
    shader.write_text(map_materials.shader_text(table.MATERIALS, 'generated by map_build.py for %s' % name))
    # q3map2 does not scan scripts/: it parses exactly the files named in
    # scripts/shaderlist.txt, so an unlisted script silently becomes "no shader"
    # and every surfaceparm (nodraw, trigger, sky) is quietly lost.
    listing = base / 'scripts' / 'shaderlist.txt'
    named = [line.strip() for line in (listing.read_text().splitlines() if listing.is_file() else [])
             if line.strip() and not line.startswith('//')]
    if name not in named:
        named.append(name)
    listing.write_text('\n'.join(named) + '\n')
    wanted = list(map_materials.images(table.MATERIALS))
    if 'SKY' in table.__dict__:
        wanted += map_materials.sky_images(table.SKY)
    staged, missing = {}, []
    for target, source in wanted:
        found = next((root / source for root in assets if (Path(root) / source).is_file()), None)
        if found is None:
            missing.append(source)
            continue
        destination = base / target
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not (destination.is_file() and destination.stat().st_size == found.stat().st_size
                and hashlib.sha256(destination.read_bytes()).hexdigest()
                == hashlib.sha256(found.read_bytes()).hexdigest()):
            shutil.copyfile(found, destination)
        staged[target] = str(found)
    if missing:
        raise RuntimeError('missing map images, generate them first: %s' % ', '.join(sorted(missing)))
    return base, staged


def author(source, work, name):
    """Model the level if the model script *or the material table* changed, then export to `.map`."""
    # Blender resolves a relative `--python` file and a relative file name against
    # its own working directory, which is the map's source directory here, so both
    # paths must be absolute or `maps/<name>` is doubled.
    #
    # The material table is an input to the model step, not only to the image
    # staging: `build_blender.py` reads it for `map_blender.world(scene, **WORLD)`
    # and for every face's shader/repeat/texwidth, all of which are baked into the
    # `.blend` as custom data.  Watching only the script's mtime silently exported
    # a scene whose worldspawn still carried the previous fog/skylight keys and
    # whose faces kept the previous scale, while the compile happily wrote new
    # images for it -- an authoring change that looked applied and was not.
    builder, blend = (source / 'build_blender.py').resolve(), (source / ('%s.blend' % name)).resolve()
    # The shape library the builder *calls* is an input to the model, not an
    # external constant: `map_blender.paint` changed what a rebuilt scene means
    # while `build_blender.py` itself sat untouched, and a watched-mtime list of
    # only the map's own files happily re-exported a scene modelled by the old
    # library and reported the change as applied.  Same failure mode the comment
    # above already documents for `materials.py`.
    # Every module the builder can load is an input, discovered rather than
    # enumerated: `textures.py` became one the day `materials.py` started reading
    # its `CRAFT` table for `repeat` and `size`, and `props.py` became one when the
    # prop table arrived.  Neither was in the hand-written list, so the texture
    # motif retune exported a scene still modelled at the previous scale and the
    # build reported the change as applied -- the exact failure this block exists
    # to prevent, reproduced by the list written to prevent it.  A glob costs
    # nothing (a spurious Blender re-model is ~90 s) and cannot miss a module that
    # has not been invented yet.
    inputs = [builder, Path(__file__).resolve().parent / 'map_blender.py']
    inputs.extend(sorted(Path(source).glob('*.py')))
    newest = max((path.stat().st_mtime for path in inputs if path.is_file()), default=0.0)
    if builder.is_file() and (not blend.is_file() or newest > blend.stat().st_mtime):
        # The furniture manifest is what `map_prop_clear.py` re-runs the placement
        # pass against offline, and it only exists when the model step is told to
        # write it.  Hand-setting DK3_BOXES_JSON for one investigation and not the
        # next is why the manifest a checker consulted was three builds old.
        run(['blender', '-b', '--python', str(builder), '--python-exit-code', '1'], cwd=str(source),
            log=work / 'blender-build.log', label='blender model',
            env={'DK3_BOXES_JSON': str(work / ('%s-boxes.json' % name))})
        # Blender 5.1 leaves a script that never parsed at exit code 0, so the
        # scene file itself is the only honest witness that the model step ran.
        if not blend.is_file() or blend.stat().st_mtime < newest:
            raise RuntimeError('%s was not rewritten by %s -- the model step said'
                               ' nothing and the export would use a stale scene'
                               % (blend, builder))
    if not blend.is_file():
        raise RuntimeError('%s is missing; write %s or model the map in the Blender GUI' % (blend, builder))
    document = work / ('%s.map' % name)
    report = work / ('%s-author.json' % name)
    _, text = run(['blender', '-b', str(blend), '--python', str(Path(__file__).resolve().parent / 'map_author.py'),
                   '--python-exit-code', '1', '--', '--out', str(document), '--report', str(report)],
                  cwd=str(source), log=work / 'blender-author.log', label='blender export')
    # Blender does not always forward a script's exit code, so the transcript and
    # the report decide whether the export actually happened.
    if 'Traceback' in text or not report.is_file() or not document.is_file():
        detail = [line for line in text.splitlines() if line.startswith(('map-author:', 'NameError', 'KeyError', 'ValueError', 'quake_map.BrushError'))][-6:]
        raise RuntimeError('the scene did not export: %s; see %s'
                           % ('; '.join(detail) or 'no report', work / 'blender-author.log'))
    drift = texture_scale_drift(document, source)
    if drift:
        raise RuntimeError(
            'exported texture scale disagrees with the material table (the scene was '
            'modelled from stale numbers): %s'
            % ', '.join('%s wants %g u, faces carry %g u' % (shader, want, tile_s)
                        for shader, (want, tile_s, _tile_t) in drift[:6]))
    return document, json.loads(report.read_text())



def declared_scales(source):
    """-> {shader path: (world units per tile, texwidth)} from the map's own table.

    Reads `maps/<name>/materials.py` the way `build_blender.py` does, so the two
    agree on what a material claims, including the defaults `map_author.py`
    applies to a tool material that names neither key.
    """
    table = source / 'materials.py'
    if not table.is_file():
        return {}
    import importlib.util
    spec = importlib.util.spec_from_file_location('dk3_map_materials', str(table))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    out = {}
    for path, entry in getattr(module, 'MATERIALS', {}).items():
        out[path] = (float(entry.get('repeat', 128.0)), float(entry.get('texwidth', 512.0)))
    return out


def texture_scale_drift(document, source, tolerance=1e-3):
    """-> [(shader, declared tile, tile the exported face actually carries)].

    `repeat` is authored as world units and reaches the engine as a face scale
    (`scale = repeat / texwidth`, `map_author.material_style`).  Both ends are
    cheap to read, so comparing them proves the whole chain: a scene modelled from
    a stale `.blend`, a table that drifted, or a compiler that rescaled a face all
    land here instead of arriving as an owner's screenshot.
    """
    want = declared_scales(source)
    if not want:
        return []
    face = re.compile(r'\)\s+(\S+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)')
    worst = {}
    for line in Path(document).read_text().splitlines():
        hit = face.search(line)
        if not hit:
            continue
        shader, _, _, _, scale_s, scale_t = hit.groups()
        declared = want.get(shader)
        if declared is None:
            continue
        tile_s, tile_t = float(scale_s) * declared[1], float(scale_t) * declared[1]
        # `.map` writes a face scale with four decimals, so the tile a face can
        # carry is quantised by 0.00005 * texwidth (0.05 u on a 1024 image).  The
        # guard has to compare at the precision the file format actually has, or a
        # correct map fails and the real drift hides behind the noise.
        grain = 5e-5 * declared[1] + tolerance * declared[0]
        if abs(tile_s - declared[0]) <= grain and abs(tile_t - declared[0]) <= grain:
            continue
        worst[shader] = (declared[0], round(tile_s, 4), round(tile_t, 4))
    return sorted(worst.items())


# q3map2 -meta is deliberately not used: when a stage flag follows the light
# options, this build folds the VIS and light passes away without running them
# and still exits 0. Three separate passes cost a little re-reading of the BSP
# and give each stage its own log, exit code and re-run boundary, so a quality
# light pass can reuse a good BSP and vis instead of recompiling the world.
def compile_stages(quality, threads, only=None):
    """-> the q3map2 passes to run, in order, optionally a subset of them.

    `only` exists because `-vis` dominates the wall clock of a full build (884 s
    measured on this map against 25 s of `-bsp` and 57 s of `-light`), while the
    change being iterated on is usually an image.  A texture-only edit does not
    move a single plane, so the visibility lump the previous `-vis` wrote is still
    true, and `-light` alone on the vis'd BSP is the honest pass.  It is not
    trusted: `inspect_bsp` still has to report `visibility`, so a relight that
    silently dropped the PVS fails the same gate a full compile does.
    """
    shared = ['-threads', str(threads)]
    visibility = shared + ['-vis'] + ([] if quality else ['-fast'])
    lighting = shared + ['-light', '-deluxe']
    lighting += ['-samples', '3', '-super', '2'] if quality else ['-fast', '-samples', '2']
    passes = [('bsp', shared + ['-bsp']), ('vis', visibility), ('light', lighting)]
    return passes if only is None else [ps for ps in passes if ps[0] in only]


def compile_map(base, work, name, quality, shaders, only=None):
    """Compile BSP, vis and light, then prove what actually came back."""
    shutil.copyfile(work / ('%s.map' % name), base / 'maps' / ('%s.map' % name))
    threads = min(8, os.cpu_count() or 4)
    transcripts = {}
    for stage, options in compile_stages(quality, threads, only):
        _, transcripts[stage] = run([Q3MAP2] + options + [('%s.map' % name)], cwd=str(base / 'maps'),
                                    home=base.parents[1], log=work / ('compile-%s.log' % stage),
                                    label='q3map2 %s' % stage)
    bsp = base / 'maps' / ('%s.bsp' % name)
    report = inspect_bsp(bsp) if bsp.is_file() else {}
    transcript = '\n'.join(transcripts.values())
    problems = [line for line in transcript.splitlines() if any(marker in line for marker in FAILURES)]
    if not bsp.is_file():
        problems.append('q3map2 wrote no BSP')
    else:
        if not report['visibility']:
            problems.append('no visibility: the map leaks or vis was skipped')
        if report['lightmap_images'] < 1:
            problems.append('no lightmaps: lighting did not run or every surface is nolightmap')
        if not report['lightgrid']:
            problems.append('no light grid: point lighting is missing')
        absent = [shader for shader in shaders if shader.encode() not in report['shader_text']]
        if absent:
            problems.append('shaders missing from the BSP: %s' % ', '.join(absent))
    if problems:
        raise RuntimeError('compile problems:\n  %s' % '\n  '.join(dict.fromkeys(problems)))
    report['passes'] = {stage: len(text.splitlines()) for stage, text in transcripts.items()}
    return bsp, report


def deluxe_mapping(lightmaps, lightmap_nums):
    """-> whether the BSP carries a light direction beside every lightmap."""
    # Ask exactly what the renderer asks (renderergl2/tr_bsp.c R_LoadLightmaps):
    # the lump is double-length and every lit surface indexes an even pair.
    # Surfaces that take vertex light or no light carry lightmapNum -1 and say
    # nothing about deluxe, so folding them into the same test calls a
    # deluxemapped map a flat one -- which is what this did on a map that
    # arrived with 18 deluxemaps in it.
    lit = [value for value in lightmap_nums if value >= 0]
    return bool(lightmaps > 1 and lit and all(value % 2 == 0 for value in lit))


def inspect_bsp(path):
    """Read back what the compiler delivered, straight out of the IBSP."""
    import numpy
    data = Path(path).read_bytes()
    version, = struct.unpack_from('<i', data, 4)
    lumps = {}
    for index, lump in enumerate(q3bsp.LUMPS):
        offset, length = struct.unpack_from('<ii', data, 8 + index * 8)
        lumps[lump] = data[offset:offset + length]
    surfaces = numpy.frombuffer(lumps['surfaces'], dtype=q3bsp.DT['surfaces'])
    leafs = numpy.frombuffer(lumps['leafs'], dtype=q3bsp.DT['leafs'])
    lightmaps = len(lumps['lightmaps']) // (128 * 128 * 3)
    numbered = [int(surface['lightmapNum']) for surface in surfaces]
    return dict(version=version, bytes=len(data),
                brushes=len(lumps['brushes']) // q3bsp.DT['brushes'].itemsize,
                surfaces=len(surfaces), drawverts=len(lumps['drawverts']) // q3bsp.DT['drawverts'].itemsize,
                lightmap_images=lightmaps, lightgrid=len(lumps['lightgrid']) > 0,
                visibility=len(lumps['visibility']) > 0,
                deluxe=deluxe_mapping(lightmaps, numbered),
                clusters=len({int(cluster) for cluster in leafs['cluster'] if cluster >= 0}),
                areas=len({int(area) for area in leafs['area'] if area >= 0}),
                shader_text=b'\n'.join(part for part in lumps['shaders'].split(b'\0') if part))


def bot_navigation(prefix, bsp, work, name):
    """Compile the bot AAS with the bundled bspc and select it per mode."""
    import navigation
    output = work / 'aas'
    if output.is_dir():
        shutil.rmtree(output)
    output.mkdir(parents=True)
    shutil.copyfile(bsp, output / ('%s.bsp' % name))
    variants, selected = navigation.navigation_variants(output / ('%s.bsp' % name))
    products, counts = {}, {}
    for stem, mode in variants:
        target = output / ('%s.aas' % stem)
        run([str(prefix / 'bin' / 'dkguard'), '--mem', '6G', '--timeout', '1800', '--',
             str(prefix / 'bin' / 'bspc'), *navigation.COMPILER_OPTIONS, '-dk3-mode', mode,
             '-bsp2aas', '%s.bsp' % name, '-output', '.'], cwd=output,
            log=work / ('aas-%s.log' % mode), label='bspc %s' % mode)
        if not target.is_file():
            raise RuntimeError('bspc wrote no AAS for mode %s; see %s' % (mode, work / ('aas-%s.log' % mode)))
        products[stem] = target
        counts[stem] = navigation.inspect_aas(target)
    selection = output / ('%s.cfg' % name)
    # The names in this file are asset names, not the map's display name: the
    # runtime (src/runtime/domain/navigation.zig `selection`) refuses any name
    # outside [a-z0-9_-], and `package` files the archives lowercased, so a map
    # authored as `japanDM` must be *selected* as `japandm`.  Writing the
    # authoring case here crashed the server at GAME_INIT with
    # `Native Zig runtime: NavigationName` before one player could connect.
    selection.write_text('dk3_navigation 1\n'
                         + ''.join('%s %s\n' % (mode, selected[mode].lower())
                                   for mode in navigation.MODES))
    return dict(aas=products, selection=selection, variants=counts)


def catalog_entry(install, name, title, modes=1):
    """-> a complete `dk3/maps.cfg` replacement: the shipped list plus this map."""
    import zipfile
    base = install / 'dk3-data.pk3'
    with zipfile.ZipFile(base) as archive:
        records = archive.read('dk3/maps.cfg').decode('utf-8').splitlines()
    records = [line for line in records if line and not line.startswith('"%s"' % name)]
    escaped = title.replace('"', "'")
    records.append('"%s" %d "%s"' % (name, modes, escaped[:96]))
    return '\n'.join(records) + '\n'


def package(name, work, bsp, navigation, staged, shader, catalog, package_path):
    """Write the installable package: map, navigation, art, shader and menu entry.

    Every delivered path is lowercased: the engine compares archive names without
    case, but the Zig runtime rejects an uppercase navigation asset name, so the
    playable name may keep its authoring case while its files never do. The mode
    selection file is mandatory, not decorative: navigation.init reads
    `dk3/navigation/<map>.cfg` unconditionally and a missing one is a fatal
    InvalidFileSize during GAME_INIT before any player can connect.
    """
    entries = [('maps/%s.bsp' % name.lower(), str(bsp))]
    entries += [('maps/%s.aas' % stem.lower(), str(path)) for stem, path in sorted(navigation['aas'].items())]
    entries += [('dk3/navigation/%s.cfg' % name.lower(), str(navigation['selection'])),
                ('scripts/%s.shader' % name.lower(), str(shader)),
                ('dk3/maps.cfg', str(catalog))]
    entries += [(target.lower(), staged[target]) for target in sorted(staged)]
    names = [entry for entry, _ in entries]
    # Ask the shipped selection file what it asks the runtime to open, and check
    # that this archive really carries it: a map that crashes the server at
    # GAME_INIT over a navigation name is not a map, and q3map2 cannot say so.
    selection_path = dict(entries)['dk3/navigation/%s.cfg' % name.lower()]
    asked = [value for row in Path(selection_path).read_text().splitlines()
             if row and not row.startswith('dk3_navigation') for value in row.split()[1:]]
    delivered = {entry.rpartition('/')[2].rpartition('.')[0]
                 for entry, _ in entries if entry.endswith('.aas')}
    unasked = sorted(set(asked) - delivered)
    if unasked:
        raise RuntimeError('the navigation selection asks for %s, which the package'
                           ' does not deliver (archives are filed lowercased)'
                           % ', '.join(unasked))
    required = {'maps/%s.bsp' % name.lower(), 'dk3/navigation/%s.cfg' % name.lower(), 'dk3/maps.cfg'}
    absent = sorted(required - set(names))
    if absent:
        raise RuntimeError('package would omit %s, which the server requires at map load' % ', '.join(absent))
    if len(names) != len(set(names)):
        raise RuntimeError('package has duplicate archive paths once lowercased')
    pk3.write_files(package_path, entries)
    return entries


def install_package(package_path, install, name):
    """-> the file placed in the isolated play tree, which is the only change.

    The installation under `--prefix` is the native development tree, never the
    preserved game. Loose pk3 files are read after the hash-checked converted
    packages and are not themselves hash-checked, so a map is *added* and every
    shipped archive keeps its recorded bytes.
    """
    target = install / ('zz-dk3-%s.pk3' % name.lower())
    if not install.is_dir():
        raise RuntimeError('%s is not an installation; build the native prefix first' % install)
    shutil.copyfile(package_path, target)
    if target.stat().st_size != package_path.stat().st_size:
        raise RuntimeError('%s is a short copy of %s' % (target, package_path))
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--map', required=True)
    parser.add_argument('--source', type=Path, default=None, help='authored map directory (default maps/<map>)')
    parser.add_argument('--prefix', type=Path, default=Path('zig-out/native-dev'))
    parser.add_argument('--work', type=Path, default=Path('zig-out/map-dev'))
    parser.add_argument('--assets', type=Path, default=None, help='generated image root (default <work>/<map>)')
    parser.add_argument('--stages', default=','.join(STAGES))
    parser.add_argument('--quality', action='store_true', help='full light sampling instead of the fast pass')
    parser.add_argument('--title', default=None, help='menu title (default: the scene message epair)')
    arguments = parser.parse_args(argv)
    name, source = arguments.map, arguments.source or Path('maps') / arguments.map
    # Every path handed to Blender must be absolute: the child runs with the map's
    # source directory as its working directory, so a relative `--out` would be
    # written under maps/<name> instead of next to the rest of the build tree.
    work, prefix = (arguments.work / name).resolve(), arguments.prefix.resolve()
    work.mkdir(parents=True, exist_ok=True)
    stages = [stage for stage in arguments.stages.split(',') if stage]
    if set(stages) - set(STAGES):
        parser.error('unknown stage in --stages')
    report = dict(map=name, source=str(source), quality=arguments.quality, stages={})
    table = load_table(source)
    roots = [arguments.assets or work / name, source / 'assets']
    try:
        if 'author' in stages or not (work / ('%s.map' % name)).is_file():
            document, authoring = author(source, work, name)
            report['stages']['author'] = dict(map=str(document), brushes=authoring['brushes'],
                                              entities=authoring['entities'], bounds=authoring['bounds'],
                                              classes=authoring['classes'], defects=authoring['defects'])
            if authoring['defects']:
                raise RuntimeError('the scene has %d defects; see %s'
                                   % (len(authoring['defects']), work / 'blender-author.log'))
        else:
            authoring = json.loads((work / ('%s-author.json' % name)).read_text())
        # The compiler tree is staged after the export so geometry can be iterated
        # before a single image exists.
        base, staged = stage_tree(work, name, table, roots)
        report['stages']['tree'] = dict(images=len(staged))
        if 'compile' in stages or 'relight' in stages:
            # Only the shaders the scene actually brushes must reach the BSP; an
            # unused table entry is a spare material, not a broken compile.
            # `relight` is the subset pass: images changed, geometry did not.
            subset = ('light',) if 'relight' in stages and 'compile' not in stages else None
            _, compiled = compile_map(base, work, name, arguments.quality,
                                      sorted('textures/%s' % key for key in authoring['shaders']),
                                      only=subset)
        else:
            # Iterating geometry before anything is compiled is the normal loop,
            # so an absent BSP is the expected state here, not a missing file.
            bsp = base / 'maps' / ('%s.bsp' % name)
            compiled = inspect_bsp(bsp) if bsp.is_file() else {}
        report['stages']['compile'] = {key: value for key, value in compiled.items() if key != 'shader_text'}
        bsp = base / 'maps' / ('%s.bsp' % name)
        navigation = None
        if 'aas' in stages or {'package', 'install'} & set(stages):
            navigation = bot_navigation(prefix, bsp, work, name)
            report['stages']['aas'] = navigation['variants']
        if {'package', 'install'} & set(stages):
            title = arguments.title or authoring.get('title') or authoring['map']
            install = prefix / 'play' / 'current' / 'share' / 'dk3'
            package_path = work / ('zz-dk3-%s.pk3' % name.lower())
            catalog = work / 'maps.cfg'          # the whole replacement file, kept for review
            catalog.write_text(catalog_entry(install, name, title))
            entries = package(name, work, bsp, navigation, staged, base / 'scripts' / ('%s.shader' % name),
                              catalog, package_path)
            report['stages']['package'] = dict(package=str(package_path),
                                               bytes=package_path.stat().st_size,
                                               entries=[entry for entry, _ in entries])
            if 'install' in stages:
                report['stages']['install'] = dict(target=str(install_package(package_path, install, name)))
    finally:
        (work / ('%s-build.json' % name)).write_text(json.dumps(report, indent=2, default=str) + '\n')
    print('map-build: %s' % name)
    for stage, details in report['stages'].items():
        print('  %-8s %s' % (stage, json.dumps(details, default=str, sort_keys=True)[:400]))
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError, RuntimeError) as error:
        print('map-build: %s' % error, file=sys.stderr)
        sys.exit(1)
