/* SPDX-License-Identifier: GPL-2.0-or-later
 * Authored room IDs map to the already bundled OpenAL EFX preset definitions.
 * Styles 0..4 retain the existing native interface; 5..30 are authored IDs 0..25.
 */
#ifndef DK3_SOUND_REVERB_H
#define DK3_SOUND_REVERB_H
#include "../thirdparty/openal-soft-1.24.3/include/AL/efx-presets.h"
static const EFXEAXREVERBPROPERTIES dk3RoomPresets[26] = {
    EFX_REVERB_PRESET_GENERIC, EFX_REVERB_PRESET_PADDEDCELL,
    EFX_REVERB_PRESET_ROOM, EFX_REVERB_PRESET_BATHROOM,
    EFX_REVERB_PRESET_LIVINGROOM, EFX_REVERB_PRESET_STONEROOM,
    EFX_REVERB_PRESET_AUDITORIUM, EFX_REVERB_PRESET_CONCERTHALL,
    EFX_REVERB_PRESET_CAVE, EFX_REVERB_PRESET_ARENA,
    EFX_REVERB_PRESET_HANGAR, EFX_REVERB_PRESET_CARPETEDHALLWAY,
    EFX_REVERB_PRESET_HALLWAY, EFX_REVERB_PRESET_STONECORRIDOR,
    EFX_REVERB_PRESET_ALLEY, EFX_REVERB_PRESET_FOREST,
    EFX_REVERB_PRESET_CITY, EFX_REVERB_PRESET_MOUNTAINS,
    EFX_REVERB_PRESET_QUARRY, EFX_REVERB_PRESET_PLAIN,
    EFX_REVERB_PRESET_PARKINGLOT, EFX_REVERB_PRESET_SEWERPIPE,
    EFX_REVERB_PRESET_UNDERWATER, EFX_REVERB_PRESET_DRUGGED,
    EFX_REVERB_PRESET_DIZZY, EFX_REVERB_PRESET_PSYCHOTIC
};
static const EFXEAXREVERBPROPERTIES *DK3_RoomPreset(int style) {
    return style >= 5 && style <= 30 ? &dk3RoomPresets[style - 5] : NULL;
}
#endif
