// SPDX-License-Identifier: GPL-2.0-or-later
//! Persistent party behavior and shared native locomotion state.
const policy = @import("actor_catalog").companions;
pub const State = struct {
    identity: policy.Identity,
    carrying: bool = false,
    enabled: bool = true,
    order: policy.Order = .follow,
    owner: u32 = 0,
    target: u32 = 0,
    destination: [3]f32 = @splat(0),
    authored: policy.Authored = .none,
    animation_until: ?i64 = null,
    after_teleport: policy.Order = .follow,
    stopped: bool = false,
    next_ms: i64 = 0,
    last_ms: i64 = 0,
    death_reported: bool = false,
    motor: @import("player_move.zig").Player = .{},
    jump_started_ms: i64 = 0,
    selected_weapon: u5 = 0,
    collecting: u32 = 0,
    collect_forced: bool = false,
    collect_scan_ms: i64 = 0,
    collect_until_ms: i64 = 0,
    avoided_item: u32 = 0,
    avoid_until_ms: i64 = 0,
    yielding_until_ms: i64 = 0,
    yield_position: [3]f32 = @splat(0),
};
